Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_bcm_snp_breast.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/bcm_snp_breast.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_europdx_wgs_brca.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/europdx_wgs_brca.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_europdx_wgs_crc.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/europdx_wgs_crc.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_hci_snp_breast.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/hci_snp_breast.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_hci_wes_breast.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/hci_wes_breast.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_bladder.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_bladder.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_breast.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_breast.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_colorectal.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_colorectal.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_gbm.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_gbm.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_luad.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_luad.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_lusc.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_lusc.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_melanoma.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_melanoma.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_otherlung.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_otherlung.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_othertumor.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_othertumor.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_ovarian.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_ovarian.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snp_sarcoma.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snp_sarcoma.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_jax_snu_wes_gastric.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/jax_snu_wes_gastric.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_mdacc_wes_luad.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/mdacc_wes_luad.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_mdacc_wes_lusc.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/mdacc_wes_lusc.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_mdacc_wes_otherlung.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/mdacc_wes_otherlung.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_bladder.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_bladder.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_colorectal.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_colorectal.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_headneck.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_headneck.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_lung.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_lung.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_othertumor.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_othertumor.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_pancreas.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_pancreas.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_renal.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_renal.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_sarcoma.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_sarcoma.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_pdmr_wes_skin.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/pdmr_wes_skin.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_sibs_snp_hcc.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/sibs_snp_hcc.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_wistar_wes_melanoma.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/wistar_wes_melanoma.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_wustl_wes_breast.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/wustl_wes_breast.txt
Rscript logr_ichor.R -i /fh/fast/ha_g/projects/PDX/matrices_full_set_1mb_severe/PDX_armMatrix_wustl_wes_pancreatic.rds --ploidy "c(2,3)" --cores 8 -o results/ &> logr_ichor_logs/wustl_wes_pancreatic.txt
